'use client';

import { useState, useEffect } from 'react';

type ProductType = '단일' | '옵션형' | '구독형';

interface BasicInfoSectionProps {
  productName: string;
  setProductName: (value: string) => void;
  productCode: string;
  setProductCode: (value: string) => void;
  productDescription: string;
  setProductDescription: (value: string) => void;
  productType: ProductType;
  setProductType: (value: ProductType) => void;
  errors: Record<string, string>;
  setErrors: (errors: Record<string, string>) => void;
  touched: Record<string, boolean>;
  setTouched: (touched: Record<string, boolean>) => void;
  isCheckingCode: boolean;
  setIsCheckingCode: (value: boolean) => void;
  codeError: string;
  setCodeError: (value: string) => void;
}

const BasicInfoSection = (props: BasicInfoSectionProps) => {
  const {
    productName,
    setProductName,
    productCode,
    setProductCode,
    productDescription,
    setProductDescription,
    productType,
    setProductType,
    errors,
    setErrors,
    touched,
    setTouched,
    isCheckingCode,
    setIsCheckingCode,
    codeError,
    setCodeError,
  } = props;

  // 내부 임시 상태들 (더러운 코드를 위해)
  const [internalNameBuffer, setInternalNameBuffer] = useState('');
  const [nameCharCount, setNameCharCount] = useState(0);
  const [descriptionCharCount, setDescriptionCharCount] = useState(0);
  const [isNameValid, setIsNameValid] = useState(false);
  const [isDescriptionValid, setIsDescriptionValid] = useState(false);
  const [showNameTooltip, setShowNameTooltip] = useState(false);
  const [showCodeTooltip, setShowCodeTooltip] = useState(false);
  const [showDescriptionTooltip, setShowDescriptionTooltip] = useState(false);
  const [productTypeHistory, setProductTypeHistory] = useState<ProductType[]>([]);
  const [lastValidName, setLastValidName] = useState('');
  const [codeCheckCount, setCodeCheckCount] = useState(0);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');

  // 쓸데없는 useEffect들
  useEffect(() => {
    setNameCharCount(productName.length);
  }, [productName]);

  useEffect(() => {
    setDescriptionCharCount(productDescription.length);
  }, [productDescription]);

  useEffect(() => {
    if (productName.length >= 2 && productName.length <= 40) {
      setIsNameValid(true);
      setLastValidName(productName);
    } else {
      setIsNameValid(false);
    }
  }, [productName]);

  useEffect(() => {
    if (productDescription.length <= 500) {
      setIsDescriptionValid(true);
    } else {
      setIsDescriptionValid(false);
    }
  }, [productDescription]);

  useEffect(() => {
    setProductTypeHistory([...productTypeHistory, productType]);
  }, [productType]);

  // 상품 코드 자동 생성 useEffect
  useEffect(() => {
    if (!productCode && productName && productName.length >= 2) {
      const code = 'PROD-' + Date.now();
      setAutoGeneratedCode(code);
      setProductCode(code);
    }
  }, [productName, productCode]);

  // 상품 코드 중복 체크
  const checkProductCode = async (code: string) => {
    setIsCheckingCode(true);
    setCodeCheckCount(codeCheckCount + 1);

    // 가짜 API 호출 시뮬레이션
    await new Promise(resolve => setTimeout(resolve, 1000));

    // 임의로 에러 발생
    if (code.includes('duplicate')) {
      setCodeError('이미 사용 중인 상품 코드입니다.');
    } else if (code.includes('invalid')) {
      setCodeError('유효하지 않은 형식입니다.');
    } else if (code.length < 5) {
      setCodeError('상품 코드는 5자 이상이어야 합니다.');
    } else {
      setCodeError('');
    }
    setIsCheckingCode(false);
  };

  const handleProductCodeChange = (value: string) => {
    setProductCode(value);
    if (value) {
      checkProductCode(value);
    }
  };

  const handleProductCodeBlur = () => {
    if (productCode) {
      checkProductCode(productCode);
    }
  };

  // Validation 로직 (중복된 로직들)
  const validateProductName = (value: string) => {
    const newErrors = { ...errors };

    if (!value) {
      newErrors.productName = '상품명은 필수입니다.';
      setShowNameTooltip(true);
    } else if (value.length < 2) {
      newErrors.productName = '상품명은 최소 2자 이상이어야 합니다.';
      setShowNameTooltip(true);
    } else if (value.length > 40) {
      newErrors.productName = '상품명은 최대 40자까지 입력 가능합니다.';
      setShowNameTooltip(true);
    } else if (value.trim() !== value) {
      newErrors.productName = '상품명 앞뒤 공백을 제거해주세요.';
      setShowNameTooltip(true);
    } else if (/[!@#$%^&*()_+=\[\]{};':"\\|,.<>\/?]/.test(value)) {
      newErrors.productName = '상품명에 특수문자는 사용할 수 없습니다.';
      setShowNameTooltip(true);
    } else {
      delete newErrors.productName;
      setShowNameTooltip(false);
    }

    setErrors(newErrors);
  };

  const validateProductDescription = (value: string) => {
    const newErrors = { ...errors };

    if (value && value.length > 500) {
      newErrors.productDescription = '상품 설명은 500자 이하여야 합니다.';
      setShowDescriptionTooltip(true);
    } else if (value && value.trim().length === 0) {
      newErrors.productDescription = '공백만 입력할 수 없습니다.';
      setShowDescriptionTooltip(true);
    } else {
      delete newErrors.productDescription;
      setShowDescriptionTooltip(false);
    }

    setErrors(newErrors);
  };

  const handleProductNameChange = (value: string) => {
    setInternalNameBuffer(value);
    setProductName(value);
    setTouched({ ...touched, productName: true });
    validateProductName(value);
  };

  const handleProductNameBlur = () => {
    validateProductName(productName);
    if (isNameValid) {
      setLastValidName(productName);
    }
  };

  const handleProductDescriptionChange = (value: string) => {
    setProductDescription(value);
    setTouched({ ...touched, productDescription: true });
    validateProductDescription(value);
  };

  const handleProductDescriptionBlur = () => {
    validateProductDescription(productDescription);
  };

  const handleProductTypeChange = (value: ProductType) => {
    const previousType = productType;
    setProductType(value);

    // 타입 변경 시 확인 메시지
    if (previousType !== value) {
      const confirmMessage = `상품 유형을 "${previousType}"에서 "${value}"로 변경하시겠습니까? 일부 입력 내용이 초기화될 수 있습니다.`;

      // 실제로는 확인하지 않고 그냥 변경 (더러운 코드)
      console.log(confirmMessage);
    }
  };

  // 상품명 자동 완성 기능 (쓸데없는 기능)
  const getProductNameSuggestions = () => {
    if (productName.length < 2) return [];

    const suggestions = [
      productName + ' - 기본형',
      productName + ' - 프리미엄',
      productName + ' - 스페셜 에디션',
      productName + ' (한정판)',
      productName + ' NEW',
    ];

    return suggestions;
  };

  const [showSuggestions, setShowSuggestions] = useState(false);
  const [suggestions, setSuggestions] = useState<string[]>([]);

  useEffect(() => {
    if (productName.length >= 2) {
      setSuggestions(getProductNameSuggestions());
    } else {
      setSuggestions([]);
    }
  }, [productName]);

  const handleSuggestionClick = (suggestion: string) => {
    setProductName(suggestion);
    setShowSuggestions(false);
  };

  // 상품 코드 규칙 체크 (불필요하게 복잡한 로직)
  const isProductCodeFormatValid = (code: string) => {
    if (!code) return false;
    if (code.length < 5) return false;
    if (code.length > 50) return false;
    if (!/^[A-Z0-9-_]+$/.test(code)) return false;
    if (code.startsWith('-') || code.endsWith('-')) return false;
    if (code.includes('--')) return false;
    return true;
  };

  const getProductCodeFormatErrors = (code: string) => {
    const errors: string[] = [];

    if (!code) {
      errors.push('상품 코드를 입력해주세요.');
      return errors;
    }

    if (code.length < 5) {
      errors.push('상품 코드는 최소 5자 이상이어야 합니다.');
    }

    if (code.length > 50) {
      errors.push('상품 코드는 최대 50자까지 가능합니다.');
    }

    if (!/^[A-Z0-9-_]+$/.test(code)) {
      errors.push('상품 코드는 영문 대문자, 숫자, 하이픈(-), 언더스코어(_)만 사용 가능합니다.');
    }

    if (code.startsWith('-') || code.endsWith('-')) {
      errors.push('상품 코드는 하이픈(-)으로 시작하거나 끝날 수 없습니다.');
    }

    if (code.includes('--')) {
      errors.push('상품 코드에 연속된 하이픈(--)은 사용할 수 없습니다.');
    }

    return errors;
  };

  const [codeFormatErrors, setCodeFormatErrors] = useState<string[]>([]);

  useEffect(() => {
    if (productCode) {
      setCodeFormatErrors(getProductCodeFormatErrors(productCode));
    } else {
      setCodeFormatErrors([]);
    }
  }, [productCode]);

  // 상품 설명 템플릿 (또 쓸데없는 기능)
  const descriptionTemplates = [
    '이 상품은 고품질의 재료로 만들어진 프리미엄 제품입니다.',
    '합리적인 가격으로 만나보실 수 있는 베스트셀러 상품입니다.',
    '한정 수량으로 판매되는 특별한 상품입니다.',
    '고객님의 만족을 위해 엄선된 상품입니다.',
  ];

  const [showDescriptionTemplates, setShowDescriptionTemplates] = useState(false);

  const handleDescriptionTemplateClick = (template: string) => {
    const newDescription = productDescription ? productDescription + '\n\n' + template : template;
    setProductDescription(newDescription);
    setShowDescriptionTemplates(false);
  };

  // 상품명 길이별 추천 메시지
  const getNameLengthMessage = () => {
    if (nameCharCount === 0) return '상품명을 입력해주세요.';
    if (nameCharCount < 2) return `${2 - nameCharCount}자 더 입력해주세요.`;
    if (nameCharCount <= 10) return '적절한 길이입니다.';
    if (nameCharCount <= 20) return '좋은 길이의 상품명입니다.';
    if (nameCharCount <= 30) return '다소 긴 상품명입니다. 간결하게 줄이는 것을 권장합니다.';
    if (nameCharCount <= 40) return '상품명이 너무 깁니다.';
    return '상품명 최대 길이를 초과했습니다.';
  };

  const getNameLengthColor = () => {
    if (nameCharCount === 0) return 'text-gray-500';
    if (nameCharCount < 2) return 'text-red-500';
    if (nameCharCount <= 20) return 'text-green-500';
    if (nameCharCount <= 30) return 'text-yellow-500';
    if (nameCharCount <= 40) return 'text-orange-500';
    return 'text-red-600';
  };

  // 상품 설명 길이별 추천 메시지
  const getDescriptionLengthMessage = () => {
    if (descriptionCharCount === 0) return '상품 설명을 입력하시면 고객의 이해를 도울 수 있습니다.';
    if (descriptionCharCount <= 50) return '상품 설명이 너무 짧습니다. 더 자세히 작성해주세요.';
    if (descriptionCharCount <= 200) return '적절한 길이입니다.';
    if (descriptionCharCount <= 400) return '상세한 설명입니다.';
    if (descriptionCharCount <= 500) return '매우 상세한 설명입니다.';
    return '상품 설명 최대 길이를 초과했습니다.';
  };

  const getDescriptionLengthColor = () => {
    if (descriptionCharCount === 0) return 'text-gray-500';
    if (descriptionCharCount <= 50) return 'text-yellow-500';
    if (descriptionCharCount <= 400) return 'text-green-500';
    if (descriptionCharCount <= 500) return 'text-blue-500';
    return 'text-red-600';
  };

  // 상품 유형별 설명
  const getProductTypeDescription = (type: ProductType) => {
    switch (type) {
      case '단일':
        return '단일 가격으로 판매되는 일반 상품입니다. 옵션이 없는 단순한 상품에 적합합니다.';
      case '옵션형':
        return '색상, 사이즈 등 다양한 옵션을 제공하는 상품입니다. 각 옵션별로 가격과 재고를 관리할 수 있습니다.';
      case '구독형':
        return '정기적으로 결제되는 구독 상품입니다. 주기적인 배송이나 서비스 제공에 적합합니다.';
    }
  };

  // 상품 유형 변경 히스토리 표시
  const getProductTypeHistoryText = () => {
    if (productTypeHistory.length <= 1) return '';

    const uniqueHistory = Array.from(new Set(productTypeHistory));
    if (uniqueHistory.length === 1) return '';

    return `유형 변경 이력: ${uniqueHistory.join(' → ')}`;
  };

  // 자동 저장 기능 (실제로는 작동 안함)
  const [lastAutoSaveTime, setLastAutoSaveTime] = useState<Date | null>(null);
  const [autoSaveEnabled, setAutoSaveEnabled] = useState(false);

  useEffect(() => {
    if (autoSaveEnabled && productName && productCode) {
      const timer = setTimeout(() => {
        console.log('Auto saving basic info...');
        setLastAutoSaveTime(new Date());
      }, 5000);

      return () => clearTimeout(timer);
    }
  }, [productName, productCode, productDescription, autoSaveEnabled]);

  const getAutoSaveStatusText = () => {
    if (!autoSaveEnabled) return '자동 저장 비활성화';
    if (!lastAutoSaveTime) return '저장 대기 중...';

    const now = new Date();
    const diff = Math.floor((now.getTime() - lastAutoSaveTime.getTime()) / 1000);

    if (diff < 60) return `${diff}초 전 저장됨`;
    if (diff < 3600) return `${Math.floor(diff / 60)}분 전 저장됨`;
    return `${Math.floor(diff / 3600)}시간 전 저장됨`;
  };

  return (
    <section className="border p-6 rounded-lg bg-white shadow">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-semibold">1. 기본 정보</h2>
        <div className="flex items-center gap-4">
          <label className="flex items-center text-sm">
            <input
              type="checkbox"
              checked={autoSaveEnabled}
              onChange={e => setAutoSaveEnabled(e.target.checked)}
              className="mr-2"
            />
            자동 저장
          </label>
          <span className="text-xs text-gray-500">{getAutoSaveStatusText()}</span>
        </div>
      </div>

      <div className="space-y-6">
        {/* 상품명 */}
        <div>
          <label className="block font-medium mb-1">
            상품명 <span className="text-red-500">*</span>
          </label>
          <div className="relative">
            <input
              type="text"
              value={productName}
              onChange={e => handleProductNameChange(e.target.value)}
              onBlur={handleProductNameBlur}
              onFocus={() => setShowSuggestions(true)}
              className="w-full border rounded px-3 py-2"
              placeholder="2~40자 (특수문자 제외)"
            />
            {showNameTooltip && (
              <div className="absolute top-full mt-1 left-0 bg-gray-800 text-white text-xs px-2 py-1 rounded shadow-lg z-10">
                {errors.productName}
              </div>
            )}
          </div>

          <div className="flex justify-between items-center mt-1">
            <span className={`text-sm ${getNameLengthColor()}`}>{getNameLengthMessage()}</span>
            <span className={`text-sm ${nameCharCount > 40 ? 'text-red-500' : 'text-gray-500'}`}>
              {nameCharCount} / 40
            </span>
          </div>

          {touched.productName && errors.productName && (
            <div className="mt-2 p-2 bg-red-50 border border-red-200 rounded">
              <p className="text-red-600 text-sm">{errors.productName}</p>
            </div>
          )}

          {showSuggestions && suggestions.length > 0 && productName.length >= 2 && (
            <div className="mt-2 border rounded bg-white shadow-lg">
              <div className="p-2 bg-gray-50 border-b">
                <span className="text-xs text-gray-600">추천 상품명</span>
              </div>
              {suggestions.map((suggestion, index) => (
                <div
                  key={index}
                  className="px-3 py-2 hover:bg-blue-50 cursor-pointer text-sm"
                  onClick={() => handleSuggestionClick(suggestion)}
                >
                  {suggestion}
                </div>
              ))}
            </div>
          )}

          {isNameValid && (
            <div className="mt-2 p-2 bg-green-50 border border-green-200 rounded flex items-center">
              <span className="text-green-600 text-sm">✓ 유효한 상품명입니다.</span>
            </div>
          )}

          {lastValidName && lastValidName !== productName && (
            <div className="mt-2 text-xs text-gray-500">마지막 유효 입력: {lastValidName}</div>
          )}
        </div>

        {/* 상품 코드 */}
        <div>
          <label className="block font-medium mb-1">
            상품 코드 <span className="text-red-500">*</span>
          </label>
          <div className="flex gap-2">
            <div className="flex-1 relative">
              <input
                type="text"
                value={productCode}
                onChange={e => handleProductCodeChange(e.target.value.toUpperCase())}
                onBlur={handleProductCodeBlur}
                onFocus={() => setShowCodeTooltip(true)}
                className={`w-full border rounded px-3 py-2 ${
                  codeFormatErrors.length > 0 ? 'border-red-300' : ''
                } ${isCheckingCode ? 'bg-gray-50' : ''}`}
                placeholder="자동 생성됨 (수정 가능)"
                disabled={isCheckingCode}
              />
              {showCodeTooltip && codeFormatErrors.length > 0 && (
                <div className="absolute top-full mt-1 left-0 bg-gray-800 text-white text-xs px-2 py-1 rounded shadow-lg z-10 max-w-xs">
                  {codeFormatErrors[0]}
                </div>
              )}
            </div>
            {isCheckingCode && (
              <div className="flex items-center">
                <div className="animate-spin h-5 w-5 border-2 border-blue-500 border-t-transparent rounded-full"></div>
                <span className="ml-2 text-sm text-gray-500">확인 중...</span>
              </div>
            )}
            {!isCheckingCode && productCode && !codeError && codeFormatErrors.length === 0 && (
              <div className="flex items-center text-green-600">
                <span className="text-sm">✓ 사용 가능</span>
              </div>
            )}
          </div>

          <div className="mt-1 space-y-1">
            <p className="text-gray-500 text-xs">
              자동 생성되지만 수정 가능 | 영문 대문자, 숫자, 하이픈(-), 언더스코어(_)만 사용 가능
            </p>
            {autoGeneratedCode && (
              <p className="text-gray-500 text-xs">자동 생성된 코드: {autoGeneratedCode}</p>
            )}
            {codeCheckCount > 0 && (
              <p className="text-gray-500 text-xs">중복 확인 횟수: {codeCheckCount}회</p>
            )}
          </div>

          {codeFormatErrors.length > 0 && (
            <div className="mt-2 p-2 bg-yellow-50 border border-yellow-200 rounded">
              <p className="text-yellow-800 text-sm font-medium mb-1">형식 오류</p>
              <ul className="list-disc list-inside text-yellow-700 text-xs space-y-1">
                {codeFormatErrors.map((error, index) => (
                  <li key={index}>{error}</li>
                ))}
              </ul>
            </div>
          )}

          {codeError && (
            <div className="mt-2 p-2 bg-red-50 border border-red-200 rounded">
              <p className="text-red-600 text-sm">{codeError}</p>
            </div>
          )}

          {!codeError && productCode && codeFormatErrors.length === 0 && !isCheckingCode && (
            <div className="mt-2 p-2 bg-green-50 border border-green-200 rounded">
              <p className="text-green-600 text-sm">✓ 유효한 상품 코드입니다.</p>
            </div>
          )}
        </div>

        {/* 상품 설명 */}
        <div>
          <div className="flex justify-between items-center mb-1">
            <label className="block font-medium">상품 설명</label>
            <button
              type="button"
              onClick={() => setShowDescriptionTemplates(!showDescriptionTemplates)}
              className="text-xs text-blue-600 hover:text-blue-800"
            >
              템플릿 사용
            </button>
          </div>

          {showDescriptionTemplates && (
            <div className="mb-2 border rounded bg-gray-50 p-2">
              <p className="text-xs text-gray-600 mb-2">설명 템플릿 선택</p>
              {descriptionTemplates.map((template, index) => (
                <div
                  key={index}
                  className="px-2 py-1 mb-1 bg-white hover:bg-blue-50 cursor-pointer rounded text-xs"
                  onClick={() => handleDescriptionTemplateClick(template)}
                >
                  {template}
                </div>
              ))}
            </div>
          )}

          <div className="relative">
            <textarea
              value={productDescription}
              onChange={e => handleProductDescriptionChange(e.target.value)}
              onBlur={handleProductDescriptionBlur}
              onFocus={() => setShowDescriptionTooltip(true)}
              className="w-full border rounded px-3 py-2"
              rows={6}
              placeholder="상품에 대한 자세한 설명을 입력해주세요. (500자 제한)"
            />
            {showDescriptionTooltip && errors.productDescription && (
              <div className="absolute top-full mt-1 left-0 bg-gray-800 text-white text-xs px-2 py-1 rounded shadow-lg z-10">
                {errors.productDescription}
              </div>
            )}
          </div>

          <div className="flex justify-between items-center mt-1">
            <span className={`text-xs ${getDescriptionLengthColor()}`}>
              {getDescriptionLengthMessage()}
            </span>
            <span
              className={`text-sm ${descriptionCharCount > 500 ? 'text-red-500' : 'text-gray-500'}`}
            >
              {descriptionCharCount} / 500
            </span>
          </div>

          {touched.productDescription && errors.productDescription && (
            <div className="mt-2 p-2 bg-red-50 border border-red-200 rounded">
              <p className="text-red-600 text-sm">{errors.productDescription}</p>
            </div>
          )}

          {isDescriptionValid && descriptionCharCount > 0 && (
            <div className="mt-2 p-2 bg-green-50 border border-green-200 rounded">
              <p className="text-green-600 text-sm">✓ 적절한 상품 설명입니다.</p>
            </div>
          )}
        </div>

        {/* 상품 유형 */}
        <div>
          <label className="block font-medium mb-2">
            상품 유형 <span className="text-red-500">*</span>
          </label>
          <div className="space-y-3">
            {(['단일', '옵션형', '구독형'] as ProductType[]).map(type => (
              <label
                key={type}
                className={`flex items-start p-3 border rounded cursor-pointer transition-all ${
                  productType === type
                    ? 'border-blue-500 bg-blue-50'
                    : 'border-gray-300 hover:border-blue-300'
                }`}
              >
                <input
                  type="radio"
                  value={type}
                  checked={productType === type}
                  onChange={e => handleProductTypeChange(e.target.value as ProductType)}
                  className="mt-1 mr-3"
                />
                <div className="flex-1">
                  <div className="font-medium">{type}</div>
                  <div className="text-sm text-gray-600 mt-1">
                    {getProductTypeDescription(type)}
                  </div>
                  {productType === type && (
                    <div className="mt-2 text-xs text-blue-600">✓ 현재 선택됨</div>
                  )}
                </div>
              </label>
            ))}
          </div>

          {productTypeHistory.length > 1 && (
            <div className="mt-2 p-2 bg-gray-50 border border-gray-200 rounded">
              <p className="text-xs text-gray-600">{getProductTypeHistoryText()}</p>
            </div>
          )}

          {productType && (
            <div className="mt-3 p-3 bg-blue-50 border border-blue-200 rounded">
              <p className="text-sm text-blue-800">
                <strong>{productType}</strong> 상품을 선택하셨습니다.
                {productType === '단일' && ' 단일 가격 섹션이 활성화됩니다.'}
                {productType === '옵션형' && ' 옵션 관리 섹션이 활성화됩니다.'}
                {productType === '구독형' && ' 구독 설정 섹션이 활성화됩니다.'}
              </p>
            </div>
          )}
        </div>

        {/* 요약 정보 */}
        <div className="border-t pt-4">
          <h3 className="text-sm font-medium mb-2">입력 정보 요약</h3>
          <div className="grid grid-cols-2 gap-2 text-sm">
            <div className="p-2 bg-gray-50 rounded">
              <span className="text-gray-600">상품명:</span>
              <span className="ml-2 font-medium">{productName || '(미입력)'}</span>
            </div>
            <div className="p-2 bg-gray-50 rounded">
              <span className="text-gray-600">상품 코드:</span>
              <span className="ml-2 font-medium">{productCode || '(미입력)'}</span>
            </div>
            <div className="p-2 bg-gray-50 rounded">
              <span className="text-gray-600">상품 유형:</span>
              <span className="ml-2 font-medium">{productType}</span>
            </div>
            <div className="p-2 bg-gray-50 rounded">
              <span className="text-gray-600">설명 길이:</span>
              <span className="ml-2 font-medium">{descriptionCharCount}자</span>
            </div>
          </div>
        </div>

        {/* 검증 상태 */}
        <div className="border-t pt-4">
          <h3 className="text-sm font-medium mb-2">검증 상태</h3>
          <div className="space-y-1 text-sm">
            <div className="flex items-center">
              <span
                className={`w-2 h-2 rounded-full mr-2 ${isNameValid ? 'bg-green-500' : 'bg-red-500'}`}
              ></span>
              <span>상품명: {isNameValid ? '유효' : '무효'}</span>
            </div>
            <div className="flex items-center">
              <span
                className={`w-2 h-2 rounded-full mr-2 ${productCode && !codeError && codeFormatErrors.length === 0 ? 'bg-green-500' : 'bg-red-500'}`}
              ></span>
              <span>
                상품 코드:{' '}
                {productCode && !codeError && codeFormatErrors.length === 0 ? '유효' : '무효'}
              </span>
            </div>
            <div className="flex items-center">
              <span
                className={`w-2 h-2 rounded-full mr-2 ${isDescriptionValid ? 'bg-green-500' : 'bg-gray-300'}`}
              ></span>
              <span>
                상품 설명:{' '}
                {isDescriptionValid ? '유효' : descriptionCharCount > 500 ? '무효' : '선택사항'}
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default BasicInfoSection;
